[build-system]
requires = [
    "setuptools >= 65",
    "wheel >= 0.38"
]
build-backend = "setuptools.build_meta"

[project]
name = "chaingpt"
version = "0.0.1"
dependencies = [
    "flask-restful >= 0.3.10"
]